name: meditrack
description: A new Flutter project.

publish_to: 'none' # Jangan dipublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Pastikan versi SDK Flutter Anda mendukung ini

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies - Perbarui ke versi terbaru yang stabil dan saling kompatibel
  # Gunakan versi yang lebih tinggi yang tersedia di pub.dev
  firebase_core: 4.0.0 # Perbarui ke major version 3.x.x
  firebase_auth: ^6.0.0 # Perbarui ke major version 6.x.x
  cloud_firestore: ^6.0.0 # Perbarui ke major version 6.x.x

  # Plugin dari FlutterGems.dev
  # Karena konflik 'web', kita harus memastikan fluttertoast menggunakan versi yang bekerja
  # dengan Firebase. Kita akan mencoba versi terbaru yang stabil.
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.0    
  permission_handler: ^12.0.1 # Versi ini sudah stabil di pub.dev

  # Dependencies lainnya
  # Kembali ke 8.2.8 atau 8.2.12 jika 9.x.x belum rilis.
  # Konflik 'web' antara fluttertoast dan firebase_auth_web adalah masalah utama.
  # Kita akan mencoba kembali ke 8.2.12, tetapi dengan asumsi Firebase yang baru bisa mengatasi 'web'.
  fluttertoast: ^8.2.12 # Kembali ke versi stabil terbaru di seri 8.x.x
  intl: ^0.19.0      
  syncfusion_flutter_charts: ^30.1.42 # Perbarui ke versi terbaru yang tersedia
  syncfusion_flutter_core: ^30.1.42 # Perbarui juga ini, karena charts bergantung padanya

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Ini masih yang direkomendasikan untuk Anda
  # lints: ^3.0.0 # Tidak perlu eksplisit jika sudah diatur oleh flutter_lints

flutter:
  uses-material-design: true

  assets:
    - assets/meditrack_logo.png
    - assets/doctor_illustration.png